version: 2
jobs:
  build:
    branches:
      ignore:
        - /release.*/

    docker:
      - image: circleci/ruby:2.4.1
        environment:
          RAILS_ENV: test
          RACK_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      # install dependencies
      - run:
          name: install dependencies
          command: gem install rspec

      # run tests
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            rspec .

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
